### ISSUE TITLE
安装上了之后，去谷歌商店要代理的用户名和密码呀？

### ISSUE THREAD

**Issue by pythonliuwei-root** [zcjunblog/google-access-helper2020#5]

**Comment by zcjunblog** [comment]
注册账号啊   就是白嫖他的免费流量啊兄弟

**Comment by zcjunblog** [comment]
> _No description provided._

用的哪一款

**Comment by pythonliuwei-root** [comment]
白红-谷歌服务助手1.19.9.6_0 注册了账号！也输入了就一直弹窗让 输入用户名和密码

**Comment by pythonliuwei-root** [comment]
![image](https://user-images.githubusercontent.com/42850746/126274457-c80c1dff-63fa-4358-bca3-957ec1c85121.png)

**Comment by pythonliuwei-root** [comment]
输入完注册的账号和密码就一直弹窗还让输入

**Comment by pythonliuwei-root** [comment]
我搞定了

**Comment by Yonghero** [comment]
怎么注册账号

**Comment by zcjunblog** [comment]
> 怎么注册账号

不同插件使用方法不同 仔细阅读注意事项 安装后按照提示操作即可
