### ISSUE TITLE
插件报错，无法连接

### ISSUE THREAD

**Issue by SkyWalker0006** [zcjunblog/google-access-helper2020#8]
Error handling response: TypeError: Cannot read properties of undefined (reading 'toLowerCase')

js/ss.js:1593 (匿名函数)

1593					const t = tabs[0].url.toLowerCase().match(/^[^:]+:\/\/(www\.)?([^?/\\]+)/);

**Comment by zcjunblog** [comment]
移除, 换一个 
注意: 请勿同时使用多个版本插件,容易代理冲突,装上重启浏览器等待连接不能使用就删除换其他版本尝试
